const tltList = [
  {
    country: "UK & US",
    year: "2017",
    format: [
      "Vinyl",
      "LP",
      "Album",
      "Vinyl",
      '7"',
      "45 RPM",
      "Single Sided",
      "All Media",
      "Deluxe Edition",
      "Limited Edition",
    ],
    label: [
      "Rough Trade",
      "Rough Trade",
      "Rough Trade",
      "Sleaford Mods",
      "Rough Trade Records Ltd.",
      "Rough Trade Records Ltd.",
      "West Heath Garage",
      "Rough Trade",
      "Alchemy Mastering",
      "Wipe Out Music Ltd.",
      "Optimal Media GmbH",
      "Optimal Media GmbH",
      "Optimal Media GmbH",
    ],
    type: "master",
    genre: ["Electronic", "Hip Hop", "Rock"],
    style: ["Post-Punk", "Minimal", "Thug Rap"],
    id: 1142161,
    barcode: [
      "883870092586",
      "BG54435-01 A1  RTRADLP925 A1  PUNKS NOT DEAD...",
      "BG54435-01 B1 RTRADLP925 B1  MATT@ALCHEMY ...IT IS NOW!",
      "883870092517",
      "BG63421-01 A2 SJ RTRADS925",
    ],
    user_data: {
      in_wantlist: false,
      in_collection: false,
    },
    master_id: 1142161,
    master_url: "https://api.discogs.com/masters/1142161",
    uri: "/master/1142161-Sleaford-Mods-English-Tapas",
    catno: "RTRADLPX925",
    title: "Sleaford Mods - English Tapas",
    thumb:
      "https://i.discogs.com/Mx5EBwYtUhIpa8KTADRYLTrTPeDY9MGEDrf3-GfeTxg/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTk4/NDI0NTgtMTQ4NzIw/ODU5OS04NzUwLmpw/ZWc.jpeg",
    cover_image:
      "https://i.discogs.com/HGFTSxIXHdiIbqeFwoOd4eAr1aGfZm-FWniMcmrUuQU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTk4/NDI0NTgtMTQ4NzIw/ODU5OS04NzUwLmpw/ZWc.jpeg",
    resource_url: "https://api.discogs.com/masters/1142161",
    community: {
      want: 1267,
      have: 4028,
    },
    tracklist: [
      {
        position: "A1",
        type_: "track",
        title: "Army Nights",
        duration: "3:02",
      },
      {
        position: "A2",
        type_: "track",
        title: "Just Like We Do",
        duration: "2:54",
      },
      {
        position: "A3",
        type_: "track",
        title: "Moptop",
        duration: "2:38",
      },
      {
        position: "A4",
        type_: "track",
        title: "Messy Anywhere",
        duration: "3:12",
      },
      {
        position: "A5",
        type_: "track",
        title: "Time Sands",
        duration: "3:10",
      },
      {
        position: "A6",
        type_: "track",
        title: "Snout",
        duration: "2:44",
      },
      {
        position: "B1",
        type_: "track",
        title: "Drayton Manored",
        duration: "3:36",
      },
      {
        position: "B2",
        type_: "track",
        title: "Carlton Touts",
        duration: "2:52",
      },
      {
        position: "B3",
        type_: "track",
        title: "Cuddly",
        duration: "3:44",
      },
      {
        position: "B4",
        type_: "track",
        title: "Dull",
        duration: "2:41",
      },
      {
        position: "B5",
        type_: "track",
        title: "B.H.S.",
        duration: "3:48",
      },
      {
        position: "B6",
        type_: "track",
        title: "I Feel So Wrong",
        duration: "3:10",
      },
      {
        position: "C1",
        type_: "track",
        title: "Big Trouble In Little Costa",
        duration: "2:44",
      },
    ],
  },
  {
    country: "US",
    year: "1994",
    format: ["CD", "Album"],
    label: [
      "Creation Records",
      "ERG",
      "SBK Records",
      "Creation Records Ltd.",
      "Creation Records Ltd.",
      "EMI MFG.",
      "SBK Records",
      "EMI Manufacturing (USA)",
      "Carlin Music Corp.",
      "EMI Music Publishing Ltd.",
      "Protocol Studios",
      "Courtyard Studio",
      "Whitehouse Recording Studio",
    ],
    type: "master",
    genre: ["Rock"],
    style: ["Shoegaze", "Dream Pop"],
    id: 58649,
    barcode: [
      "0 7777-88263-2 3",
      "IFPI L043",
      "IFPI 1656",
      "077778826323 · MASTERED BY EMI MFG.",
      "MIS2",
      "ifpi 1638",
    ],
    user_data: {
      in_wantlist: false,
      in_collection: false,
    },
    master_id: 58649,
    master_url: "https://api.discogs.com/masters/58649",
    uri: "/Slowdive-Souvlaki/master/58649",
    catno: "0777 7 88263 2 3",
    title: "Slowdive - Souvlaki",
    thumb:
      "https://i.discogs.com/T_bmuWcPnmcBY8MmK_QQMy4sToEJ-iScQBYssXM4HL4/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTI2/MTIxNC0xMjM0MDI5/NDI5LmpwZWc.jpeg",
    cover_image:
      "https://i.discogs.com/6M0nRvf3ExfuBznjbKOp9viSTO1XSAk1hnkdTQbqF5s/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTI2/MTIxNC0xMjM0MDI5/NDI5LmpwZWc.jpeg",
    resource_url: "https://api.discogs.com/masters/58649",
    community: {
      want: 0,
      have: 0,
    },
    tracklist: [
      {
        position: "1",
        type_: "track",
        title: "Alison",
        duration: "3:51",
      },
      {
        position: "2",
        type_: "track",
        title: "Machine Gun",
        duration: "4:29",
      },
      {
        position: "3",
        type_: "track",
        title: "40 Days",
        duration: "3:16",
      },
      {
        position: "4",
        type_: "track",
        title: "Sing",
        extraartists: [
          {
            name: "Brian Eno",
            anv: "",
            join: "",
            role: "Effects [Treatments], Keyboards",
            tracks: "",
            id: 634,
            resource_url: "https://api.discogs.com/artists/634",
          },
          {
            name: "Slowdive/Brian Eno",
            anv: "",
            join: "",
            role: "Written By",
            tracks: "",
            id: 0,
            resource_url: "",
          },
          {
            name: "Brian Eno",
            anv: "",
            join: "",
            role: "Written-By",
            tracks: "",
            id: 634,
            resource_url: "https://api.discogs.com/artists/634",
          },
          {
            name: "Slowdive",
            anv: "",
            join: "",
            role: "Written-By",
            tracks: "",
            id: 26494,
            resource_url: "https://api.discogs.com/artists/26494",
          },
        ],
        duration: "4:51",
      },
      {
        position: "5",
        type_: "track",
        title: "Here She Comes",
        extraartists: [
          {
            name: "Brian Eno",
            anv: "",
            join: "",
            role: "Effects [Treatments], Keyboards",
            tracks: "",
            id: 634,
            resource_url: "https://api.discogs.com/artists/634",
          },
        ],
        duration: "2:22",
      },
      {
        position: "6",
        type_: "track",
        title: "Souvlaki Space Station",
        extraartists: [
          {
            name: "Slowdive",
            anv: "",
            join: "",
            role: "Written-By",
            tracks: "",
            id: 26494,
            resource_url: "https://api.discogs.com/artists/26494",
          },
        ],
        duration: "5:59",
      },
      {
        position: "7",
        type_: "track",
        title: "When The Sun Hits",
        extraartists: [
          {
            name: "Martin Nichols",
            anv: "",
            join: "",
            role: "Engineer",
            tracks: "",
            id: 274318,
            resource_url: "https://api.discogs.com/artists/274318",
          },
        ],
        duration: "4:47",
      },
      {
        position: "8",
        type_: "track",
        title: "Altogether",
        duration: "3:42",
      },
      {
        position: "9",
        type_: "track",
        title: "Melon Yellow",
        extraartists: [
          {
            name: "Martin Nichols",
            anv: "",
            join: "",
            role: "Engineer",
            tracks: "",
            id: 274318,
            resource_url: "https://api.discogs.com/artists/274318",
          },
        ],
        duration: "3:55",
      },
      {
        position: "10",
        type_: "track",
        title: "Dagger",
        duration: "3:34",
      },
      {
        position: "",
        type_: "heading",
        title: "Bonus Tracks Not On Import",
        duration: "",
      },
      {
        position: "11",
        type_: "track",
        title: "Some Velvet Morning",
        extraartists: [
          {
            name: "Lee Hazlewood",
            anv: "",
            join: "",
            role: "Written-By",
            tracks: "",
            id: 225403,
            resource_url: "https://api.discogs.com/artists/225403",
          },
        ],
        duration: "3:24",
      },
      {
        position: "12",
        type_: "track",
        title: "Good Day Sunshine",
        duration: "5:08",
      },
      {
        position: "13",
        type_: "track",
        title: "Missing You",
        duration: "4:16",
      },
      {
        position: "14",
        type_: "track",
        title: "Country Rain",
        extraartists: [
          {
            name: "Rachel Goswell",
            anv: "Goswell",
            join: "",
            role: "Written-By",
            tracks: "",
            id: 228094,
            resource_url: "https://api.discogs.com/artists/228094",
          },
        ],
        duration: "3:34",
      },
    ],
  },
  {
    country: "Germany",
    year: "1999",
    format: ["Vinyl", '12"', "33 ⅓ RPM", "Album"],
    label: ["Tresor", "Dubplates & Mastering", "EFA"],
    type: "master",
    genre: ["Electronic"],
    style: ["Electro"],
    id: 535,
    barcode: [
      "TRESOR 129 A",
      "TRESOR 129 B",
      "TRESOR 129 C",
      "TRESOR 129 D",
      "718755612965",
      "LC07572",
      "GEMA",
    ],
    user_data: {
      in_wantlist: false,
      in_collection: false,
    },
    master_id: 535,
    master_url: "https://api.discogs.com/masters/535",
    uri: "/master/535-Drexciya-Neptunes-Lair",
    catno: "Tresor 129",
    title: "Drexciya - Neptune's Lair",
    thumb:
      "https://i.discogs.com/_5AGIeB3SlKet20BTCunTHGDwml5YkSd17SM2iZshgE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTEz/ODY2LTE1NDE0MzA3/ODctNzM3MC5qcGVn.jpeg",
    cover_image:
      "https://i.discogs.com/CZqoop6RV1PyNZf1DtIiyCCpfPKj-2_msOpehEe2D4g/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTEz/ODY2LTE1NDE0MzA3/ODctNzM3MC5qcGVn.jpeg",
    resource_url: "https://api.discogs.com/masters/535",
    community: {
      want: 8338,
      have: 5211,
    },
    tracklist: [
      {
        position: "A1",
        type_: "track",
        title: "Intro: Temple Of Dos De Aqua",
        duration: "1:00",
      },
      {
        position: "A2",
        type_: "track",
        title: "Andreaen Sand Dunes",
        duration: "6:15",
      },
      {
        position: "A3",
        type_: "track",
        title: "Running Out Of Space",
        duration: "1:54",
      },
      {
        position: "A4",
        type_: "track",
        title: "Universal Element",
        duration: "1:55",
      },
      {
        position: "B1",
        type_: "track",
        title: "Habitat 'O' Negative",
        duration: "5:16",
      },
      {
        position: "B2",
        type_: "track",
        title: "Funk Release Valve",
        duration: "3:06",
      },
      {
        position: "B3",
        type_: "track",
        title: "Organic Hydropoly Spores",
        duration: "2:07",
      },
      {
        position: "B4",
        type_: "track",
        title: "Draining Of The Tanks",
        duration: "2:43",
      },
      {
        position: "C1",
        type_: "track",
        title: "Surface Terrestrial Colonization",
        duration: "6:56",
      },
      {
        position: "C2",
        type_: "track",
        title: "Oxyplasmic Gyration Beam",
        duration: "4:17",
      },
      {
        position: "D1",
        type_: "track",
        title: "Triangular Hydrogen Strain",
        duration: "3:55",
      },
      {
        position: "D2",
        type_: "track",
        title: "Bottom Feeders",
        duration: "3:25",
      },
      {
        position: "D3",
        type_: "track",
        title: "C To The Power Of X + C To The Power Of X = MM = Unknown",
        duration: "2:35",
      },
    ],
  },
];

const ltList = [
  {
    country: "Netherlands",
    year: "2020",
    format: ["File", "WAV"],
    label: ["Nightwind Records", "The North Sea Institute For The Overmind"],
    type: "master",
    genre: ["Electronic"],
    style: ["Techno", "Ambient"],
    id: 1702130,
    barcode: [],
    user_data: {
      in_wantlist: false,
      in_collection: false,
    },
    master_id: 1702130,
    master_url: "https://api.discogs.com/masters/1702130",
    uri: "/Legowelt-Tips-For-Life/master/1702130",
    catno: "NW023",
    title: "Legowelt - Tips For Life",
    thumb:
      "https://i.discogs.com/WhIo07LTS1aP4st9Ot_wC_IqE7Zq3c1D2W_3cVR9-vE/rs:fit/g:sm/q:40/h:150/w:150/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTE0/OTU4MTQ4LTE1ODQ3/MjcyMTUtNDk5NC5w/bmc.jpeg",
    cover_image:
      "https://i.discogs.com/TS_3jqwM4jleov2Q2kWPdm4KWj-LWqyyOQciglwFPQ0/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTE0/OTU4MTQ4LTE1ODQ3/MjcyMTUtNDk5NC5w/bmc.jpeg",
    resource_url: "https://api.discogs.com/masters/1702130",
    community: {
      want: 23,
      have: 60,
    },
    tracklist: [
      {
        position: "1",
        type_: "track",
        title: "The Sinister Never Deceives",
        duration: "4:01",
      },
      {
        position: "2",
        type_: "track",
        title: "Dutch Polder Techno",
        duration: "5:53",
      },
      {
        position: "3",
        type_: "track",
        title: "Vamparch",
        duration: "5:49",
      },
      {
        position: "4",
        type_: "track",
        title: "Your Life Goals Are Slowly Slipping Away",
        duration: "4:33",
      },
      {
        position: "5",
        type_: "track",
        title: "Color Techno For You And Me",
        duration: "5:33",
      },
      {
        position: "6",
        type_: "track",
        title: "We Shampoo Your Dreams",
        duration: "4:09",
      },
      {
        position: "7",
        type_: "track",
        title: "Arcade Breeze (Living In The Rain)",
        duration: "5:08",
      },
      {
        position: "8",
        type_: "track",
        title: "Dune Is A Great Movie No Matter What People Say",
        duration: "4:38",
      },
      {
        position: "9",
        type_: "track",
        title: "Buying ZIPdisks In Memphis",
        duration: "3:56",
      },
      {
        position: "10",
        type_: "track",
        title: "Where You Want To Go",
        duration: "5:52",
      },
      {
        position: "11",
        type_: "track",
        title: "In The Dominion Of Melchezedik",
        duration: "6:05",
      },
      {
        position: "12",
        type_: "track",
        title: "Acing The Test",
        duration: "4:18",
      },
    ],
  },
];

export const initialTLTList = tltList;
export const initialLTList = ltList;
